apollo:
  meta: http://192.168.1.197:7555
  appId: agreementpay-hook-service
  namespaceName: application,sentinel
  cluster: default
version: "v1"
sentinel:
  app:
    name: agreementpay-hook-service
    type: 0
  log:
    dir: "~/logs/csp"
    pid: false
    metric:
      maxFileCount: 14
      flushIntervalSec: 1
  stat:
    system:
      collectIntervalMs: 1000
