app:
  name: config-service
db:
  url:   "plat:mTAerlrufO@tcp(192.168.1.205:3600)/dida_apollo_plus_config?charset=utf8mb4&parseTime=True&loc=Local"
  debug: true
log:
  filename:  logs/server.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: true
http:
  port: 9090
  mode: release
