app:
  id: apollo-plus-portal
  name: apollo-plus-portal
db:
  url:   "plat:mTAerlrufO@tcp(192.168.1.205:3600)/dida_apollo_plus_portal?charset=utf8mb4&parseTime=True&loc=Local"
  debug: true
log:
  filename:  logs/server.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: true
http:
  port: 9200
  mode: release
meta:
  TEST: http://192.168.1.197:7555,http://192.168.1.195:7555
  ALIYUN: http://192.168.1.197:7555,http://192.168.1.195:7555
  ONLINE: http://192.168.1.197:7555,http://192.168.1.195:7555


